//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Exp()
    * f1 -> <EOF>
    */
   public void visit(Goal n);

   /**
    * f0 -> Term()
    * f1 -> [ Exp2() ]
    */
   public void visit(Exp n);

   /**
    * f0 -> PlusExp()
    *       | MinusExp()
    */
   public void visit(Exp2 n);

   /**
    * f0 -> "+"
    * f1 -> Term()
    * f2 -> [ Exp2() ]
    */
   public void visit(PlusExp n);

   /**
    * f0 -> "-"
    * f1 -> Term()
    * f2 -> [ Exp2() ]
    */
   public void visit(MinusExp n);

   /**
    * f0 -> Factor()
    * f1 -> [ Term2() ]
    */
   public void visit(Term n);

   /**
    * f0 -> TimesExp()
    *       | DivExp()
    */
   public void visit(Term2 n);

   /**
    * f0 -> "*"
    * f1 -> Factor()
    * f2 -> [ Term2() ]
    */
   public void visit(TimesExp n);

   /**
    * f0 -> "/"
    * f1 -> Factor()
    * f2 -> [ Term2() ]
    */
   public void visit(DivExp n);

   /**
    * f0 -> Num()
    *       | ParExp()
    */
   public void visit(Factor n);

   /**
    * f0 -> <NUMBER>
    */
   public void visit(Num n);

   /**
    * f0 -> "("
    * f1 -> Exp()
    * f2 -> ")"
    */
   public void visit(ParExp n);

}

